/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.actions.workshop

class App {
    val greeting: String
        get() {
            return "From Kotlin!"
        }
}

fun main(args: Array<String>) {
    val message = App().greeting
    println("${args[0]} ${args[1]} - $message")
}
