name: update readme

on:
  repository_dispatch:
    types:
      - UpdateReadme

jobs:
  update-readme-action:
    name: create pull request
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.client_payload.branch }}
      MESSAGE: ${{ github.event.client_payload.message }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: add bullet to readme
        run: |
          echo "* ${MESSAGE}" >> README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TEST_GITHUB_TOKEN }}
          commit-message: "docs(README): append message ${{ env.MESSAGE}}"
          branch-suffix: timestamp
          title: "docs(README): append message ${{ env.MESSAGE}}"
          labels: |
            docsUpdate
          body: |
            Event
            ```
            ${{ toJson(github.event.client_payload) }}
            ```