name: test 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'release/**'


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.random.outputs.number }}
    steps:
      - name: echo message
        id: random
        run: |
          random=$((1 + $RANDOM % 6))
          echo "##[set-output name=number::$random"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: start build
        run: |
          echo "Starting build job.... ${{needs.setup.outputs.number}} "

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: build app
        run: |
          ./gradlew build

      - name: end build
        run: |
          echo "eding build job"
